
// Objective-C API for talking to the following Go packages
//
//	alpha.2se.com/sdk
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Sdk_FRAMEWORK_H__
#define __Sdk_FRAMEWORK_H__

#include "Sdk.objc.h"
#include "Universe.objc.h"

#endif
